drop user ADMIN_SUPER_USER;

CREATE USER ADMIN_SUPER_USER IDENTIFIED BY NeuBoston2024#;

GRANT CONNECT, RESOURCE TO ADMIN_SUPER_USER;

ALTER USER ADMIN_SUPER_USER QUOTA UNLIMITED ON DATA;

GRANT CREATE USER TO ADMIN_SUPER_USER;
GRANT ALTER USER TO ADMIN_SUPER_USER;
GRANT DROP USER TO ADMIN_SUPER_USER;
