CREATE USER ADMIN_SUPER_USER IDENTIFIED BY NeuBoston2024#;

GRANT CONNECT, RESOURCE TO ADMIN_SUPER_USER WITH ADMIN OPTION;

ALTER USER ADMIN_SUPER_USER QUOTA UNLIMITED ON DATA;

GRANT CREATE USER, ALTER USER, DROP USER TO ADMIN_SUPER_USER;