-- Clean up script file
-- "USERS" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'USERS';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('USERS TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE USERS';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/

-- "CANDIDATES" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'CANDIDATES';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('CANDIDATES TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE CANDIDATES';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/

-- "WORK_EXP" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'WORK_EXP';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('WORK_EXP TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE WORK_EXP';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/

-- "COMPANIES" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'COMPANIES';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('COMPANIES TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE COMPANIES';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/

-- "RECRUITERS" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'RECRUITERS';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('RECRUITERS TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE RECRUITERS';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/

-- "SKILLS" TABLE
SET SERVEROUTPUT ON;
DECLARE TABLE_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*)
     INTO TABLE_EXISTS
     FROM USER_TABLES
  WHERE TABLE_NAME = 'SKILLS';
 IF 
    TABLE_EXISTS > 0
    THEN 
     dbms_output.put_line ('SKILLS TABLE WILL BE DROPPED');
    EXECUTE IMMEDIATE 'DROP TABLE SKILLS';
  ELSE
     dbms_output.put_line ('GOOD TO GO TO NEXT STEP');
END IF;
END;
/