-- INSERT FILE SCRIPT
-- TABLE USERS
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (1, 'JOHN', 'DEER', 'jdeer@jmail.com', 'JDEER', 'jdeer123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (2, 'JAMES', 'RODRIGUEZ', 'jrodriguez@jmail.com', 'JRODRI', 'jrodri123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (3, 'LIONEL', 'TURNER', 'lturner@jmail.com', 'LTURNER', 'lturner123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (4, 'CHRIS', 'JONES', 'cjones@jmail.com', 'CJONES', 'cjones123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (5, 'ADAM', 'BLAKE', 'ablake@jmail.com', 'ABLAKE', 'ablake123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (6, 'ALLEN', 'LUGO', 'alugo@jmail.com', 'ALUGO', 'alugo123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (7, 'ROSS', 'MILLER', 'rmiller@jmail.com', 'RMILLER', 'rmiller123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (8, 'DAVID', 'AUSTIN', 'daustin@jmail.com', 'DAUSTIN', 'daustin123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (9, 'MAT', 'HENRY', 'mhenry@jmail.com', 'MHENRY', 'mhenry123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (10, 'RAVIN', 'PATEL', 'rpatel@jmail.com', 'RPATEL', 'rpatel123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (11, 'RODRI', 'KING', 'rking@jmail.com', 'RKING', 'rking123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (12, 'RAY', 'HOPE', 'rhope@jmail.com', 'RHOPE', 'rhope123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (13, 'BELLA', 'QUEEN', 'bqueen@jmail.com', 'BQUEEN', 'bqueen123');
INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (14, 'ALEXANDER', 'ARNOLD', 'aarnold@jmail.com', 'AARNOLD', 'aarnold123');

--TABLE CANDIDATES
INSERT INTO CANDIDATES (CANDIDATE_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD)
VALUES (1, 'JOHN', 'DEER', 'jdeer@jmail.com', 'JDEER', 'jdeer123');
