-- USER table creation
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(70) NOT NULL,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL
);

-- CANDIDATE table creation
CREATE TABLE CANDIDATES (
    CANDIDATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   -- ADDRESS 
    PHONE VARCHAR2(15),
    AGE NUMBER(2),
    GENDER VARCHAR2(15),
    VETERAN VARCHAR2(100),
    DISABILITY VARCHAR2(100),
    DATE_OF_JOIN DATE
);

-- WORK EXPERIENCE table creation - Candidate's Work Experience
CREATE TABLE WORK_EXP (
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    JOB_TITLE VARCHAR2(100) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    DESCRIPTION VARCHAR2(2000)
);

-- COMPNANY table creation
CREATE TABLE COMPANIES (
    COMPANY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    PHONE VARCHAR2(15)
);

-- RECRUITER table creation
CREATE TABLE RECRUITERS (
    RECRUITER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

-- SKILLS table creation - all the skills present on the platform
CREATE TABLE SKILLS (
    SKILL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SKILL_NAME VARCHAR2(100) NOT NULL
);