CREATE OR REPLACE PROCEDURE REC_USER_CREATION (
    PI_FNAME USERS.FIRSTNAME%TYPE,
    PI_LNAME USERS.LASTNAME%TYPE,
    PI_USERNAME USERS.USERNAME%TYPE,
    PI_EMAIL USERS.EMAIL%TYPE DEFAULT NULL,
    PI_PASSWORD USERS.PASSWORD%TYPE,
    PI_COMPANY_NAME COMPANIES.NAME%TYPE
) AS
    COMPANY_ID NUMBER DEFAULT -1;
    V_COMPANY_DOES_NOT_EXIST EXCEPTION;
    V_NEW_USER_ID USERS.USER_ID%TYPE;
    V_USER_EXISTS NUMBER DEFAULT 0;
BEGIN
        SELECT 1 INTO V_USER_EXISTS
        FROM USERS
        WHERE LOWER(USERNAME) = LOWER(PI_USERNAME);
        
        
        SELECT COMPANY_ID INTO COMPANY_ID
        FROM COMPANIES
        WHERE LOWER(NAME) = LOWER(PI_COMPANY_NAME);
        
    --    IF COMPANY_ID = -1 THEN 
    --        RAISE V_COMPANY_DOES_NOT_EXIST;
    --    END IF;
        
        IF V_USER_EXISTS = 0 THEN
        -- Insert New User
            INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME,EMAIL, PASSWORD)
            VALUES (PI_FNAME, PI_LNAME, PI_USERNAME, PI_EMAIL, PI_PASSWORD)
            RETURNING USER_ID INTO V_NEW_USER_ID;
            
            INSERT INTO RECRUITERS (USER_ID, COMPANY_ID)
            VALUES (V_NEW_USER_ID, COMPANY_ID);
            
            DBMS_OUTPUT.PUT_LINE('USER CREATED SUCCESSFULLY. USER_ID:' || V_NEW_USER_ID);
    
        ELSE
            -- Update Existing User
            UPDATE USERS
            SET
                FIRSTNAME = CASE WHEN PI_FNAME IS NOT NULL THEN PI_FNAME ELSE FIRSTNAME END,
                LASTNAME = CASE WHEN PI_LNAME IS NOT NULL THEN PI_LNAME ELSE LASTNAME END,
                PASSWORD = CASE WHEN PI_PASSWORD IS NOT NULL THEN PI_PASSWORD ELSE PASSWORD END
            WHERE LOWER(USERNAME) = LOWER(PI_USERNAME);
            
            IF SQL%ROWCOUNT = 0 THEN
                DBMS_OUTPUT.PUT_LINE(PI_USERNAME || ' USERNAME DOES NOT EXIST.');
            ELSE
                DBMS_OUTPUT.PUT_LINE('USER UPDATED SUCCESSFULLY. USERNAME:' || PI_USERNAME);
            END IF;
            
        END IF;
    
    COMMIT;
    
EXCEPTION
    -- Handle exceptions
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: COMPANY DOES NOT EXIST');
        
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        
END REC_USER_CREATION;
/


SELECT * FROM USERS;
BEGIN
    REC_USER_CREATION(
        PI_FNAME => 'AAKASH',
        PI_LNAME => 'CHOTHANI',
        PI_USERNAME => 'ACHOKSY',
        PI_PASSWORD => 'ACHOKSY@12345',
        PI_COMPANY_NAME => 'IBM'
);
END;
/