--VIEWS/REPORT 
--VIEW 1: JOBS APPLIED HISTORY FOR A CANDIDATE
DROP VIEW JOBS_APPLIED_HISTORY;
CREATE VIEW JOBS_APPLIED_HISTORY AS
SELECT 
    c.CANDIDATE_ID,
    u.FIRSTNAME,
    u.LASTNAME,
    j.REQ_ID AS JOB_ID,
    j.JOB_TITLE,
    j.JOB_DESCRIPTION,
    j.STATUS
FROM CANDIDATES c
JOIN USERS u
ON c.CANDIDATE_ID = u.CANDIDATE_ID
JOIN JOB_REQUISITION j 
ON j.REQ_ID = c.CANDIDATE_ID
WHERE 
    j.STATUS = 'Completed'
AND c.CANDIDATE_ID = ' ';
    
--VIEW 2: JOBS CREATED HISTORY BY A RECRUITER
DROP VIEW JOBS_CREATED_HISTORY;
CREATE VIEW JOBS_CREATED_HISTORY AS
SELECT r.RECRUITER_ID,
    u.FIRSTNAME,
    u.LASTNAME,
    j.REQ_ID AS JOB_ID,
    j.JOB_TITLE,
    j.DATE_POSTED,
    j.STATUS
FROM  RECRUITERS r
JOIN USERS u
ON r.RECRUITER_ID = u.RECRUITER_ID
JOIN JOB_REQUISITION j 
ON r.RECRUITER_ID = j.REQ_ID
WHERE r.RECRUITER_ID = ' ';

--VIEW 3: ALL APPLIED CANDIDATES INFO FOR ONE JOB 
DROP VIEW CANDIDATES_JOB_APPLIED;
CREATE VIEW CANDIDATES_JOB_APPLIED AS
SELECT j.REQ_ID AS JOB_ID,
    j.JOB_TITLE,
    c.CANDIDATE_ID,
    u.FIRSTNAME,
    u.LASTNAME,
    u.EMAIL,
    c.PHONE,
    c.DATE_OF_JOIN
FROM JOB_REQUISITION j
JOIN CANDIDATES ca 
ON j.REQ_ID = c.CANDIDATE_ID
JOIN USERS u
ON c.CANDIDATE_ID = u.CANDIDATE_ID
ORDER BY j.REQ_ID;

--VIEW 4: LIST OF OPEN JOBS FOR A RECRUITER
DROP VIEW JOBS_OPEN;
CREATE VIEW JOBS_CREATED_HISTORY AS
SELECT r.RECRUITER_ID,
    u.FIRSTNAME,
    u.LASTNAME,
    j.REQ_ID AS JOB_ID,
    j.JOB_TITLE,
    j.DATE_POSTED,
    j.STATUS
FROM  RECRUITERS r
JOIN USERS u
ON r.RECRUITER_ID = u.RECRUITER_ID
JOIN JOB_REQUISITION j 
ON r.RECRUITER_ID = j.REQ_ID
WHERE r.RECRUITER_ID = ' '
AND j.STATUS = 'Open';

--VIEW5: ALL PROFILE DETAILS FOR A CANDIDATE
DROP VIEW CANDIDATE_PROFILE
CREATE VIEW CANDIDATE_PROFILE AS
SELECT c.CANDIDATE_ID,
    u.FIRSTNAME,
    u.LASTNAME,
    u.EMAIL,
    ....
FROM CANDIDATES c
JOIN USERS u
ON c.CANDIDATE_ID = u.CANDIDATE_ID
JOIN EDUCATION e
ON c.CANDIDATE_ID = e.CANDIDATE_ID  
JOIN ADDRESS a 
ON c.CANDIDATE_ID = ca.ADDRESS_ID
JOIN WORK_EXP we 
ON c.CANDIDATE_ID = we.COMPANY_NAME
WHERE CANDIDATE_ID = ' ';