--VIEWS/REPORT
--VIEW 1: JOBS-APPLIED HISTORY
CREATE VIEW JOBS_APPLIED_HISTORY AS
SELECT
    CA.CANDIDATE_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CANDIDATE_NAME,
    JR.REQ_ID,
    JR.JOB_TITLE,
    JR.COMPANY_ID,
    COM.NAME,
    CA.DATE_APPLIED,
    CA.STATUS
    FROM
        CANDIDATE_APPLICATION CA
    JOIN
        CANDIDATES C ON CA.CANDIDATE_ID = C.CANDIDATE_ID
    JOIN 
        JOB_REQUISITION JR ON CA.REQ_ID = JR.REQ_ID
    JOIN
        COMPANIES COM ON JR.COMPANY_ID = COM.COMPANY_ID;
        
--VIEW 2: JOBS-CREATED HISTORY
CREATE VIEW JOBS_CREATED_HISTORY AS
SELECT
    JR.RECRUITER_ID,
    R.FIRST_NAME || ' ' || C.LAST_NAME AS RECRUITER_NAME,
    COM.NAME AS COMPANY_NAME,
    JR.REQ_ID,
    JR.JOB_TITLE,
    JR.JOB_DESCRIPTION,
    JR.DATE_POSTED,
    JR.STATUS
FROM
    JOB_REQUISITION JR
JOIN
    RECRUITERS R ON JR.RECRUITER_ID = R.RECRUITER_ID
JOIN
    COMPANIES COM ON JR.COMPANY_ID = COM.COMPANY_ID;


--VIEW 3: CANDIDATES-JOBS APPLIED
CREATE VIEW CANDIDATES_JOBS_APPLIED AS
SELECT
    JR.REQ_ID,
    JR.JOB_TITLE,
    CA.CANDIDATE_ID,
    C.FIRSTNAME || ' ' || C.LASTNAME AS CANDIDATE_NAME,
    C.PHONE AS PHONE_NUMBER,
    C.EMAIL AS EMAIL,
    CA.STATUS AS APPLICATION_STATUS,
    CA.WILLING_TO_RELOCATE,
    E.UNIVERSITY_NAME,
    E.DEGREE,
    E.MAJOR,
    WE.COMPANY_NAME AS LAST_COMPANY_NAME,
    WE.JOB_TITLE AS LAST_JOB_TITLE
FROM
    CANDIDATE_APPLICATION CA
JOIN
    CANDIDATES C ON CA.CANDIDATE_ID = C.CANDIDATE_ID
JOIN
    JOB_REQUISITION JR ON CA.REQ_ID = JR.REQ_ID
LEFT JOIN
    EDUCATION E ON C.CANDIDATE_ID = E.CANDIDATE_ID
LEFT JOIN 
    WORK_EXP WE ON C.CANDIDATE_ID = WE.CANDIDATE_ID;


-- VIEW 4: JOBS-OPEN
CREATE VIEW JOBS_OPEN AS
SELECT
    JR.REQ_ID,
    JR.JOB_TITLE,
    JR.JOB_DESCRIPTION,
    JR.DATE_POSTED,
    JR.APPLICATION_DEADLINE,
    JR.STATUS AS JOB_STATUS,
    COM.NAME AS COMPANY_NAME,
    JR.EXPECTED_START_DATE,
    JR.RELOCATION_ALLOWANCE
FROM 
    JOB_REQUISITION JR
JOIN 
    COMPANIES COM ON JR.COMPANY_ID = COM.COMPANY_ID
WHERE 
    JR.STATUS = 'open';


-- VIEW 5: CANDIDATE-PROFILE
CREATE VIEW CANDIDATE_PROFILE AS
SELECT
    C.CANDIDATE_ID,
    C.FIRSTNAME || ' ' || C.LAST_NAME AS CANDIDATE_NAME,
    C.EMAIL,
    C.PHONE,
    C.AGE,
    C.GENDER,
    C.VETERAN,
    C.DISABILITY,
    C.DATE_OF_JOIN,
    A.STREET1,
    A.STREET2,
    A.CITY,
    A.STATE,
    A.ZIPCODE,
    E.UNIVERSITY_NAME,
    E.DEGREE,
    E.MAJOR,
    WE.COMPANY_NAME AS LAST_COMPANY,
    WE.JOB_TITLE AS LAST_JOB_TITLE,
    S.SKILL_NAME
FROM 
    CANDIDATES C
LEFT JOIN
    ADDRESS A ON C.ADD_ID = A.ADDRESS_ID
LEFT JOIN 
    EDUCATION E ON C.CANDIDATE_ID = E.CANDIDATE_ID
LEFT JOIN 
    WORK_EXP WE ON C.CANDIDATE_ID = WE.CANDIDATE_ID
LEFT JOIN 
    CANDIDATE_SKILLS CS ON C.CANDIDATE_ID = CS.CANDIDATE_ID
LEFT JOIN 
    SKILLS S ON CS.SKILL_ID = S.SKILL_ID;