-- CANDIDATE USER creation
DECLARE
    ROWS_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO ROWS_COUNT
    FROM ALL_USERS
    WHERE USERNAME = 'CANDIDATE';
    
    IF ROWS_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER CANDIDATE CASCADE';
        dbms_output.put_line('"CANDIDATE" user dropped.');
    END IF;
    EXECUTE IMMEDIATE 'CREATE USER CANDIDATE IDENTIFIED BY NeuBoston2024#';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO CANDIDATE';
    
    -- Access to tables
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON USERS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON ADDRESS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON CANDIDATES TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON WORK_EXP TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON EDUCATION TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON RESUME TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON SKILLS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, DELETE ON CANDIDATE_SKILLS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON COMPANIES TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON RECRUITERS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON JOB_REQUISITION TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT ON CANDIDATE_APPLICATION TO CANDIDATE';
    
    -- Acccess to views
    EXECUTE IMMEDIATE 'GRANT SELECT ON JOBS_APPLIED_HISTORY TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON OPEN_JOBS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON CANDIDATE_PROFILE TO CANDIDATE';
    
    -- Access to packages
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON USER_MGMT.CREATE_USER TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON USER_MGMT.UPDATE_USER TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON ADD_MGMT.CREATE_ADDRESS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_MGMT.CREATE_CANDIDATE_PROFILE TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_MGMT.UPDATE_CANDIDATE_PROFILE TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_MGMT.DEACTIVATE_CANDIDATE TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_APP_MGMT.CREATE_CAN_APP TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_APP_MGMT.CANDIDATE_STATUS TO CANDIDATE';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_APP_MGMT.WITHDRAW_APP TO CANDIDATE';
    
    DBMS_OUTPUT.PUT_LINE('"CANDIDATE" user created successfully.');

EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Something went wrong: Error Code ' || SQLCODE || ' - ' || SQLERRM);
END;
/


-- RECRUITER USER creation
DECLARE
    ROWS_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO ROWS_COUNT
    FROM ALL_USERS
    WHERE USERNAME = 'RECRUITER';
    
    IF ROWS_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER RECRUITER CASCADE';
        DBMS_OUTPUT.PUT_LINE('"RECRUITER" user dropped.');
    END IF;
    EXECUTE IMMEDIATE 'CREATE USER RECRUITER IDENTIFIED BY NeuBoston2024#';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO RECRUITER';
    
     -- Access to tables
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON USERS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON ADDRESS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON CANDIDATES TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON WORK_EXP TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON EDUCATION TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON RESUME TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON SKILLS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON CANDIDATE_SKILLS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON COMPANIES TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON RECRUITERS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON JOB_REQUISITION TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE (STATUS) ON CANDIDATE_APPLICATION TO RECRUITER';
    
    -- Acccess to views
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON JOBS_CREATED_HISTORY TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON CANDIDATES_JOBS_APPLIED TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON JOBS_OPEN TO RECRUITER';
    DBMS_OUTPUT.PUT_LINE('"RECRUITER" user created successfully.');
    
    -- Access to packages
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON USER_MGMT.UPDATE_USER TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON REC_MGMT.CREATE_RECRUITER_PROFILE TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON REC_MGMT.UPDATE_RECRUITER_PROFILE TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON JOB_REQ_MGMT.CREATE_JOB_REQ TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON JOB_REQ_MGMT.UPDATE_REQ_STATUS TO RECRUITER';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CAN_APP_MGMT.UPDATE_APPLICATION_STATUS TO RECRUITER';
    
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Something went wrong: Error Code ' || SQLCODE || ' - ' || SQLERRM);
END;
/