-- Test script for PKG_CAN_APP_MGMT.WITHDRAW_APP
DECLARE    
    C_VALID_CAN_ID CONSTANT CANDIDATE_APPLICATION.CANDIDATE_ID%TYPE := 2;
    C_VALID_REQ_ID CONSTANT CANDIDATE_APPLICATION.REQ_ID%TYPE := 2;
BEGIN
    UTIL_PKG.ADD_NEW_LINE('TESTING PKG_CAN_APP_MGMT.WITHDRAW_APP PROCEDURE');
    
    DBMS_OUTPUT.PUT_LINE('1. Testing for NULL CANDIDATE_ID:');
    WITHDRAW_APP(NULL, '');
    
    DBMS_OUTPUT.PUT_LINE('2. Testing for NULL RECRUITER_ID:');
    WITHDRAW_APP(23, '');
END;
/
