PROCEDURE CREATE_CAN_APP (
    PI_CAN_ID IN CANDIDATES.CANDIDATE_ID%TYPE, 
    REQ_ID IN JOB_REQUISTION.REQ_ID%TYPE, 
    STATUS IN CANDIDATE_APPLICATION.STATUS%TYPE DEFAULT 'submitted'
) AS
BEGIN
    INSERT INTO CANDIDATE_APPLICATION
        (CANDIDATE_ID, REQ_ID, STATUS)
    VALUES
        (PI_CAN_ID, REQ_ID, STATUS);
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creating application: ' || SQLERRM);
END;
/

-- APP CREATION (DUP VALIDATION)
-- CAN APPLY/ WITHDRAW
-- CAN ACCEPTS/ REJECTS